language: node_js
node_js:
- stable
cache:
- yarn
install:
- yarn install
script:
- yarn build
branches:
  only:
  - master
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local_dir: dist
  default_text_charset: utf-8
